### PR TITLE
Lots of refactoring, code analysis and coding standards corrections, and a unit test project is added.

### PR DESCRIPTION
**Pull request by jessehallam**
Decided to tackle your project just for fun. I've written a whole muck of changes which conform to Microsoft coding standards. In particular:
- Added XML docs on several properties and methods.
- Rewrote some docs to use standardized verbiage.
- Ran Visual Studio Code Analysis and cleared all CA-series warnings.
- Added additional error checking on method parameters (is offset + count > length?)
- Added a basic Unit Test package. Ran unit tests against the original solution (f7d579516144ddf824fbead6b61027c628289ec7) and against my fork with all changes merged (5865338b380151d22134c7a93ee101fb90405a66); tests passed.

Notes on tests: Coverage is at ~40%. I might add additional tests if I find the time.
The main test reads the MP3Stream (ala the README) and MD5 hashes the PCM output. If the hash is good, the whole algorithm is thought to be in a good state.

### CODE REVIEW

**Comment by jessehallam** [comment]
Also note that I was forced to remove "virtual" specifiers from several properties and methods in order to conform with CA2214. See the attached URI for rationale if necessary.

This caused no compliation issues (i.e. they aren't being overriden) so you should be OK. Some heavier refactoring would be required to make them overridable without violating CA2214.

**Comment by ZaneDubya** [comment]
@jessehallam Thank you for taking the time to do this - looks great! I will check out your changes and integrate after work today. :)

**Comment by jessehallam** [comment]
You're welcome. If these changes fit your quality standards and you're satisfied with the changes, I'll do more later.

**Comment by ZaneDubya** [comment]
@jessehallam More than satisfied, these are great. I've made one change. Please take a look at [Buffer16BitStereo.cs:71](https://github.com/ZaneDubya/MP3Sharp/blob/jessehallam-formatting-docs-unittests-warnings/MP3Sharp/Buffer16BitStereo.cs#L71) (link is to my edit). I've changed the error condition from >= to >. Is this correct?

**Comment by jessehallam** [comment]
@ZaneDubya That's absolutely correct. In fact, I made that change locally and for some odd reason I didn't push it. Sorry about that, and good eye.

**Comment by ZaneDubya** [comment]
Ok! Looks good, merging. If you see any further opportunities for improvement - there are many, I know! - please add them.

**Pull request merged**
